/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as LayoutExportRouteImport } from './routes/_layout/export'
import { Route as LayoutLogsRouteImport } from './routes/_layout/logs'
import { Route as LayoutTaxonomyRouteImport } from './routes/_layout/taxonomy'
import { Route as LayoutUploadRouteImport } from './routes/_layout/upload'
import { Route as LayoutErrorsErrorRouteImport } from './routes/_layout/errors/$error'
import { Route as LayoutProductsIndexRouteImport } from './routes/_layout/products.index'
import { Route as LayoutProductsIdRouteImport } from './routes/_layout/products.$id'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutExportRoute = LayoutExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutLogsRoute = LayoutLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutTaxonomyRoute = LayoutTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutUploadRoute = LayoutUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutErrorsErrorRoute = LayoutErrorsErrorRouteImport.update({
  id: '/errors/$error',
  path: '/errors/$error',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutProductsIndexRoute = LayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutProductsIdRoute = LayoutProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => LayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/categories': typeof LayoutCategoriesRoute
  '/export': typeof LayoutExportRoute
  '/logs': typeof LayoutLogsRoute
  '/taxonomy': typeof LayoutTaxonomyRoute
  '/upload': typeof LayoutUploadRoute
  '/errors/$error': typeof LayoutErrorsErrorRoute
  '/products/$id': typeof LayoutProductsIdRoute
  '/products/': typeof LayoutProductsIndexRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/categories': typeof LayoutCategoriesRoute
  '/export': typeof LayoutExportRoute
  '/logs': typeof LayoutLogsRoute
  '/taxonomy': typeof LayoutTaxonomyRoute
  '/upload': typeof LayoutUploadRoute
  '/': typeof LayoutIndexRoute
  '/errors/$error': typeof LayoutErrorsErrorRoute
  '/products/$id': typeof LayoutProductsIdRoute
  '/products': typeof LayoutProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/export': typeof LayoutExportRoute
  '/_layout/logs': typeof LayoutLogsRoute
  '/_layout/taxonomy': typeof LayoutTaxonomyRoute
  '/_layout/upload': typeof LayoutUploadRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/errors/$error': typeof LayoutErrorsErrorRoute
  '/_layout/products/$id': typeof LayoutProductsIdRoute
  '/_layout/products/': typeof LayoutProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/categories'
    | '/export'
    | '/logs'
    | '/taxonomy'
    | '/upload'
    | '/errors/$error'
    | '/products/$id'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/categories'
    | '/export'
    | '/logs'
    | '/taxonomy'
    | '/upload'
    | '/'
    | '/errors/$error'
    | '/products/$id'
    | '/products'
  id:
    | '__root__'
    | '/_layout'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_layout/categories'
    | '/_layout/export'
    | '/_layout/logs'
    | '/_layout/taxonomy'
    | '/_layout/upload'
    | '/_layout/'
    | '/_layout/errors/$error'
    | '/_layout/products/$id'
    | '/_layout/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/export': {
      id: '/_layout/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof LayoutExportRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/logs': {
      id: '/_layout/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LayoutLogsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/taxonomy': {
      id: '/_layout/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof LayoutTaxonomyRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/upload': {
      id: '/_layout/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof LayoutUploadRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/errors/$error': {
      id: '/_layout/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof LayoutErrorsErrorRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/products/': {
      id: '/_layout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof LayoutProductsIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/products/$id': {
      id: '/_layout/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof LayoutProductsIdRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutExportRoute: typeof LayoutExportRoute
  LayoutLogsRoute: typeof LayoutLogsRoute
  LayoutTaxonomyRoute: typeof LayoutTaxonomyRoute
  LayoutUploadRoute: typeof LayoutUploadRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutErrorsErrorRoute: typeof LayoutErrorsErrorRoute
  LayoutProductsIdRoute: typeof LayoutProductsIdRoute
  LayoutProductsIndexRoute: typeof LayoutProductsIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutExportRoute: LayoutExportRoute,
  LayoutLogsRoute: LayoutLogsRoute,
  LayoutTaxonomyRoute: LayoutTaxonomyRoute,
  LayoutUploadRoute: LayoutUploadRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutErrorsErrorRoute: LayoutErrorsErrorRoute,
  LayoutProductsIdRoute: LayoutProductsIdRoute,
  LayoutProductsIndexRoute: LayoutProductsIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
